name: Check for new Droid versions
on:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * 1'
permissions:
  id-token: write
  contents: write
jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - run: pip install requests
      - run: python .github/scripts/check_for_new_version.py
      - name: Check for new version
        id: check_versions
        run: |
          if [ -n "$(git ls-files --others --exclude-standard)" ]; then
            echo "new-version=true" >> $GITHUB_OUTPUT
          else
            echo "No new version of the signature files was found"
            echo "new-version=false" >> $GITHUB_OUTPUT
          fi
      - name: Create PR if there are changes
        if: steps.check_versions.outputs.new-version == 'true'
        run: |
          git config --global user.email 181243999+tna-da-bot@users.noreply.github.com
            git config --global user.name tna-da-bot
            git checkout -b $BRANCH_NAME
            git add -A 
            git commit -m "Droid version bump"
            git push -u origin $BRANCH_NAME
            gh pr create --title "Droid Version Bump" --body "Bump Droid Version"
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_PAT }}
          BRANCH_NAME: droid-version-bump-${{ github.run_id }}${{ github.run_attempt }}
